on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.x'
    - name: Generate coverage report
      run: |
        pip install coverage
        pip install -q -e .
        coverage run -m unittest discover tests
        coverage xml

    - name: Coveralls
      uses: coverallsapp/github-action@v2